fix(watch): make delete watcher work
go-jira/jira pull request #454
Opened 2021-12-08 15:08 UTC by georgettica

the apispec noted it should use 'username' and not 'accountId'

2021-12-08 15:12 UTC, georgettica commented
@catskul can you look?
at least peer review can help 🤞

2022-10-19 16:27 UTC, nyarly commented
@georgettica Can you link the spec? It looks straightforward but it's hard to comment without context

2022-10-27 00:22 UTC, nyarly requested changes
I think in general we should be switching to `accountId` for anything but privately hosted instances. What bug is this addressing?

2022-10-27 00:22 UTC, nyarly commented on issue.go
> +	uri += fmt.Sprintf("?username=%s", user)
Per the docs:
```
username
string
This parameter is no longer available. See the deprecation notice for details.
```
Jira is transitioning wholesale to the (sadly opaque) `accountId`.

2022-11-02 08:08 UTC, closed without merging

2022-11-02 16:03 UTC, nyarly commented on issue.go
> +	uri += fmt.Sprintf("?username=%s", user)
Or something. When I was first starting out with go-jira this was a new issue, but the way the Jira ecosystem is, we probably need a better solution. Could we a) set up a maintainer team or b) enable discussions here - I think this is a bigger design issue that we can usefully resolve in PR comments.