Replace github.com/tmc/keyring  with github.com/dougEfresh/keyring
go-jira/jira pull request #460
Opened 2022-04-20 06:25 UTC by dougEfresh

github.com/tmc/keyring uses an archived and outdated dbus lib: https://github.com/guelfey/go.dbus

I have forked keyring and updated to use github.com/godbus/dbus/v5

https://github.com/godbus/dbus

2022-04-20 06:33 UTC, dougEfresh commented
I do have an open PR to tmc:
https://github.com/tmc/keyring/pull/21 if you want to wait and use that instead

2022-04-20 08:06 UTC, georgettica commented
This seems like a trivial change, let's wait and see the response..
If the upstream changes we will bump up.
If not we will add the fork and track the PR upstream

2022-04-20 08:24 UTC, georgettica requested changes
I am not sure this error is problematic, but can you take a look to see if it reproduces locally / there is a PR to fix it?
If so I will merge it before merging this

2022-04-20 18:33 UTC, georgettica commented
I think a local https://github.com/nektos/act should make sure it works.
Ty! (Didn't check it works really)

2022-05-02 18:15 UTC, bkane-msft commented
Unfortunately, https://github.com/tmc/keyring does not support Windows. In addition, the last commit to tmc/keyring was 2017, so it remains to be seen whether any one is around to merge https://github.com/tmc/keyring/pull/21 .  

I made #459 to propose using https://github.com/zalando/go-keyring for keyring management in `go-jira` because it seems to be maintained. it looks like [they updated dbus support](https://github.com/zalando/go-keyring/commits/master) on  Feb 23, 2022 ). Importantly for me, zalando/go-keyring  already supports Windows.

@dougEfresh , what are your thoughts on using zalando/go-keyring for go-jira? Then you get updated dbus support "for free" without needing to maintain a fork and I get Windows support "for free" as well.

As I stated in #459  I'm happy to do the work integrating zalando/go-keyring in go-jira. I *think* it'll be easy. I'd also be super happy if you want to do this integration work @dougEfresh :D

2022-08-29 18:09 UTC, bkane-msft commented
Just made https://github.com/go-jira/jira/pull/467 to use `zalando/go-keyring` for keyring support (updates Linux support, adds Windows support).

2026-04-03 16:30 UTC, closed without merging